### ISSUE TITLE
0.1.0 on crates.io has the wrong description and repository link

### ISSUE THREAD

**Issue by pthariensflame** [Alexhuszagh/i256-rs#37]
It seems like it was registered with some metadata from `half-rs` instead:
<img width="924" alt="Screenshot 2024-12-24 at 2 21 07 PM" src="https://github.com/user-attachments/assets/39208b8d-aa19-4afe-b133-5d184cc15609" />
<img width="317" alt="Screenshot 2024-12-24 at 2 21 35 PM" src="https://github.com/user-attachments/assets/ad98f33a-c4ac-4e86-9a91-fd6f4b12b7cd" />

**Comment by Alexhuszagh** [comment]
Thank you, fixing now.
